name: Build Enbilulu Docker image

on: [push]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prep
        run: |
          echo "BUILD_VER=1.2.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.NUGET_PUBLISH_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            - ghcr.io/${{ github.repository }}:${{ env.BUILD_VER }}
            - - ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}