name: Build Enbilulu Docker image

on: 
  push:
    branches: ['main', 'build_defs']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
  BUILD_VER: 1.2.${{github.run_number}}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.NUGET_PUBLISH_TOKEN }}
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.BUILD_VER}}}}