name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      env: # Or as an environment variable
        nuget_publish_token: ${{ secrets.NUGET_PUBLISH_TOKEN }}
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release\
        dotnet nuget push /home/runner/work/enbilulu/enbilulu/libEnbilulu/bin/Release/libEnbilulu.*.nupkg -s github -k ${env:nuget_publish_token}